### ISSUE TITLE
how much lower than the python or caffe and other architecture

### ISSUE THREAD

**Issue by niujiaopeng** [bryanyzhu/deepOF#6]
Thank you for your great job!
I have two questions:
1. You said your tensorflow implementation are lower than pytorch and caffe, does it matter a lot?
2.In your paper "Hidden Two-Stream Convolutional Networks for Action Recognition" , you use a much smaller architecture than flownetS,  do you test a smaller architecture in this paper?  and the corresponding EPE ,fps ?
thank you

**Comment by bryanyzhu** [comment]
Hi, 

(1) I remember the difference is like 0.5 epe. Does matter a lot if you just want to use it. But it matters if you want to achieve SOTA and write a paper.

(2) I also tested the small architecture. It doesn't matter on flying chairs, but matter on sintel. On flying chairs, the performance is only 0.3 epe lower. but on sintel, it is 1.5 epe lower. I guess it is because sintel has a lot of large motions which is hard for such a small network to learn. 

For fps, the small model is much faster, like 5 times faster than flownet.

**Comment by niujiaopeng** [comment]
Thank you very much for your reply!
