### ISSUE TITLE
image warp

### ISSUE THREAD

**Issue by yqNLP** [bryanyzhu/deepOF#7]
Hi, I am working on estimating optical flow using cnn and I found your excellent work. I have opened several issues in gluon-cv, so probably u remember me.

My issue is the warp operation of image. Basically, warp means input image1 and optcial flow, output image2. And u said in the paper that 

> The inverse warp is performed using a spatial transformer module [13] inside the CNN. 

I try to find the following code, which seems not related to spatial transformer:
https://github.com/bryanyzhu/deepOF/blob/7d6c12b9a697fef96719d0cfaf89fee98a2b7f91/sintelWrapFlow.py#L537

so, probably I didn't find the right code, and could u tell me where's the inverse warp operation in your code? Also, I am interesting about the above code, can u give some references about image warp as I counldn't fully understand some lines in the `warp` operation. 
Thanks in advance!

**Comment by bryanyzhu** [comment]
Hi, the location you found is correct, it is our code for image warping. Image warping is part of spatial transformer module, because it is an affine transformation. If you are using TensorFlow, it has a builtin function for this now, https://www.tensorflow.org/addons/api_docs/python/tfa/image/dense_image_warp.

Basically, the warp operation is move points from image2 back to image1, based on the optical flow. However, optical flow is usually not integer, so there is a chance that the points moved back is not on the grid. So we need to do a bilinear interpolation.

**Comment by yqNLP** [comment]
Thanks for your expainantions.
